name: ZJU-nCov-Hitcarder Sample

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
          username: [ZJU_USERNAME]
          password: [ZJU_PASSWORD]
          dingtalk_token: [DINGTALK_TOKEN]
          include:
          - username: ZJU_USERNAME
            password: ZJU_PASSWORD
            dingtalk_token: DINGTALK_TOKEN
            pushplus_token: ''
            serverchan_key: SERVERCHAN_KEY
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Working
        uses: Long0x0/zju-ncov-hitcarder@0.0.3
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          dingtalk_token: ${{ secrets[matrix.dingtalk_token] }}
          pushplus_token: ${{ secrets[matrix.pushplus_token] }}
          serverchan_key: ${{ secrets[matrix.serverchan_key] }}
